-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: 20260517_clean_legacy_handles
--
-- Cleans influencer handles generated by the old broken implementation that
-- appended a random underscore suffix (e.g. "zara_mpoxu5rt").
--
-- Strategy:
--   1. Identify records where handle matches `word_[a-z0-9]{4,10}`.
--   2. Strip the suffix — keep only the word before the underscore.
--   3. Update display_name and name to match the clean handle.
--   4. Skip any row where the clean handle is already taken by another record
--      for the same user — those will remain legacy until manually resolved
--      (edge case: extremely unlikely since the old code was a one-off bug).
-- ─────────────────────────────────────────────────────────────────────────────

-- Preview (dry run — reads only):
-- SELECT id, user_id, handle,
--        split_part(handle, '_', 1) AS clean_handle
-- FROM ai_influencers
-- WHERE handle ~ '^[a-z]+_[a-z0-9]{4,10}$';

-- Actual cleanup:
WITH cleaned AS (
  SELECT
    id,
    user_id,
    handle,
    split_part(handle, '_', 1) AS clean_handle
  FROM ai_influencers
  WHERE handle ~ '^[a-z]+_[a-z0-9]{4,10}$'
),
safe_to_update AS (
  -- Only update rows where the clean handle is not already taken by another
  -- influencer belonging to the same user.
  SELECT c.id, c.clean_handle
  FROM cleaned c
  WHERE NOT EXISTS (
    SELECT 1
    FROM ai_influencers other
    WHERE other.user_id = c.user_id
      AND other.handle  = c.clean_handle
      AND other.id     != c.id
  )
)
UPDATE ai_influencers ai
SET
  handle       = s.clean_handle,
  display_name = initcap(s.clean_handle),
  name         = initcap(s.clean_handle)
FROM safe_to_update s
WHERE ai.id = s.id;
