-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: 20260518_clean_prefix_handles
--
-- Cleans influencer handles generated by the old AESTHETIC_PREFIXES fallback
-- system (e.g. "heyzara" → "zara", "heygabriela" → "gabriela",
-- "realzara" → "zara", "itszara" → "zara").
--
-- Known prefixes to strip: hey, real, its, by, the, iam, hi, go
--
-- Strategy:
--   1. Identify records where handle starts with a known prefix followed by
--      at least 2 lowercase letters (to avoid false positives on short names
--      that happen to start with 'by' or 'go').
--   2. Strip the prefix — keep only the name portion.
--   3. Update display_name and name to title-case of the clean handle.
--   4. Skip any row where the clean handle is already taken by another record
--      for the same user (extremely unlikely, but safe).
-- ─────────────────────────────────────────────────────────────────────────────

-- Preview (dry run — read only to verify before applying):
-- SELECT id, user_id, handle,
--   regexp_replace(
--     handle,
--     '^(hey|real|its|by|the|iam|hi|go)([a-z]{2,})$',
--     '\2'
--   ) AS clean_handle
-- FROM ai_influencers
-- WHERE handle ~ '^(hey|real|its|by|the|iam|hi|go)[a-z]{2,}$';

WITH prefix_stripped AS (
  SELECT
    id,
    user_id,
    handle,
    regexp_replace(
      handle,
      '^(hey|real|its|by|the|iam|hi|go)([a-z]{2,})$',
      '\2'
    ) AS clean_handle
  FROM ai_influencers
  WHERE handle ~ '^(hey|real|its|by|the|iam|hi|go)[a-z]{2,}$'
    -- Exclude handles that don't actually change (i.e. the regex didn't match)
    AND handle != regexp_replace(
      handle,
      '^(hey|real|its|by|the|iam|hi|go)([a-z]{2,})$',
      '\2'
    )
),
safe_to_update AS (
  -- Only update rows where the clean handle is not already taken by another
  -- influencer belonging to the same user.
  SELECT p.id, p.clean_handle
  FROM prefix_stripped p
  WHERE NOT EXISTS (
    SELECT 1
    FROM ai_influencers other
    WHERE other.user_id = p.user_id
      AND other.handle  = p.clean_handle
      AND other.id     != p.id
  )
)
UPDATE ai_influencers ai
SET
  handle       = s.clean_handle,
  display_name = initcap(s.clean_handle),
  name         = initcap(s.clean_handle)
FROM safe_to_update s
WHERE ai.id = s.id;
